# Generated by Django 6.0 on 2026-01-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_deal_dealsection_dealitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deal',
            new_name='DailyDeal',
        ),
    ]
