# Generated by Django 6.0 on 2026-01-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_rename_deal_dailydeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why People Choose Us?', max_length=150)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='why_section/')),
            ],
        ),
        migrations.CreateModel(
            name='WhyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='why_section/features/')),
                ('heading', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='food.whysection')),
            ],
        ),
    ]
