# Generated by Django 6.0 on 2026-01-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_whysection_whyfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whysection',
            name='main_image',
        ),
        migrations.AddField(
            model_name='whysection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whysection',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='features/')),
                ('description', models.TextField(blank=True, null=True)),
                ('why', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='food.whysection')),
            ],
        ),
        migrations.DeleteModel(
            name='WhyFeature',
        ),
    ]
