# Generated by Django 6.0 on 2026-01-12 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_whysection_main_image_whysection_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whysection',
            name='description',
        ),
        migrations.AddField(
            model_name='whysection',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='why_section/'),
        ),
        migrations.AlterField(
            model_name='whysection',
            name='title',
            field=models.CharField(default='Why People Choose Us?', max_length=200),
        ),
        migrations.CreateModel(
            name='WhyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='why_section/features/')),
                ('heading', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='food.whysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
