# Generated by Django 6.0 on 2026-01-15 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_whysection_description_whysection_main_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDealsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Popular Deals', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PopularDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='popular_deals/')),
                ('title', models.CharField(help_text='Short title (one line)', max_length=80)),
                ('description', models.CharField(help_text='Short description (2–3 lines max)', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='food.populardealssection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
