# Generated by Django 6.0 on 2026-01-15 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_populardealssection_populardeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='our_special/')),
                ('description', models.CharField(max_length=220)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='populardeal',
            name='description',
            field=models.CharField(help_text='Short description (2–3 lines max)', max_length=180),
        ),
        migrations.CreateModel(
            name='OurSpecialCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='food.ourspecial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
