# Generated by Django 6.0 on 2026-02-25 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_remove_item_price_item_description_itemvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('daily_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.dailydeal')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.itemvariant')),
                ('our_special', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.ourspecial')),
                ('popular_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.populardeal')),
            ],
        ),
    ]
