# Generated by Django 6.0 on 2026-02-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
