# Generated by Django 6.0 on 2026-03-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_order_status_order_tracking_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
