# Generated by Django 6.0 on 2026-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=8),
        ),
    ]
