# Generated by Django 6.0 on 2026-03-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_backfill_order_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='customer_cancel_window_minutes',
            field=models.PositiveIntegerField(default=2, help_text='Customers can cancel their order only within this many minutes after placing it.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tracking_visibility_after_delivery_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Keep delivered orders visible in customer tracking for this many minutes after delivery.'),
        ),
    ]
