# Generated by Django 6.0 on 2026-03-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tracking_visibility_after_cancellation_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Keep cancelled orders visible in customer tracking for this many minutes after cancellation.'),
        ),
    ]
