# Generated by Django 6.0 on 2026-03-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0028_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('default', 'Default'), ('olive', 'Olive'), ('sunset', 'Sunset')], default='default', help_text='Theme applied across the customer-facing website.', max_length=20),
        ),
    ]
