# Generated by Django 6.0 on 2026-03-11 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0029_sitesettings_active_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_auto_response',
            field=models.TextField(blank=True, default='Thanks for reaching out. Our team will reply shortly.', help_text='This message is sent once automatically when a customer starts a new chat.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_is_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable customer live chat on the website.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('default', 'Default'), ('light', 'Light'), ('olive', 'Olive'), ('sunset', 'Sunset')], default='default', help_text='Theme applied across the customer-facing website.', max_length=20),
        ),
        migrations.CreateModel(
            name='LiveChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('display_name', models.CharField(default='Anonymous User', max_length=120)),
                ('is_authenticated_user', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Chat Thread',
                'verbose_name_plural': 'Live Chat Threads',
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Support'), ('system', 'Auto')], max_length=20)),
                ('message_text', models.TextField(max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='food.livechatthread')),
            ],
            options={
                'verbose_name': 'Live Chat Message',
                'verbose_name_plural': 'Live Chat Messages',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
